### ISSUE TITLE
Missing expected right click behavior

### ISSUE THREAD

**Issue by sierralvb** [usu-access/pilot-feedback#6]
When you right-click on documents in the left sidebar of Pilot, you get a Pilot-specific command list, not the typical right-click behavior. The main problem I find with this is that the ability to right click and open a page in a new tab is one you don't realize how much you do it until you can't. This does also impact other functionality tho, for example if you have a browser plugin where you have to right-click content to activate the plugin. 

**To Reproduce**
1. Right click any document (not folder) on the left sidebar of a Pilot page.

**Screenshots**
What a normal right-click menu looks like:
![normal right click](https://github.com/usu-accessibility/Pilot-Feedback/assets/166452991/b2e6d325-ae44-44b7-8ff3-8940e5f688b5)

What Pilot's right-click menu looks like:
![pilot right click](https://github.com/usu-accessibility/Pilot-Feedback/assets/166452991/e8760dec-26ad-4aae-bd55-24132fcfbacd)

**Comment by cphillipsusu** [comment]
https://feedback.pilot.io/b/nvk3wxmr/feature-requests/default-browser-right-click-behavior-missing

**Comment by sririe** [comment]
@cphillipsusu @sierralvb We are adding an option to the right-click contextual menu to allow opening a document or folder in a new tab (in-progress).

If you would prefer the default browser right-click behavior, we can add a feature flag to your account that would disable the Pilot menu. What would your preference be here?

**Comment by sririe** [comment]
@cphillipsusu @sierralvb: We've pushed an update to production with modified right-click behavior. You will now see a new option in the contextual menu: "Open in new tab". 

Let us know if this works for you, or if you would like to have the Pilot right-click menu disabled altogether in favor of the default browser menu for right-click.

**Comment by cphillipsusu** [comment]
Thank you! Functionally at least this definitely closes this issue - there may be an issue with accessibility of this method - but if there is, we will bring that up in a separate issue.
